import { ROLES } from "./roles.js";
import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_TENANT,

    PERMISSIONS.CREATE_DASHBOARD,
    PERMISSIONS.UPDATE_DASHBOARD,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.DELETE_DASHBOARD,

    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.VIEW_USER,

    PERMISSIONS.CREATE_TRAINER,
    PERMISSIONS.UPDATE_TRAINER,
    PERMISSIONS.DELETE_TRAINER,
    PERMISSIONS.VIEW_TRAINER,

    PERMISSIONS.CREATE_DIETITIAN,
    PERMISSIONS.UPDATE_DIETITIAN,
    PERMISSIONS.DELETE_DIETITIAN,
    PERMISSIONS.VIEW_DIETITIAN,

    PERMISSIONS.CREATE_CLIENT,
    PERMISSIONS.UPDATE_CLIENT,
    PERMISSIONS.DELETE_CLIENT,
    PERMISSIONS.VIEW_CLIENT,

    PERMISSIONS.CREATE_MEMBERSHIP,
PERMISSIONS.UPDATE_MEMBERSHIP,
PERMISSIONS.DELETE_MEMBERSHIP,
PERMISSIONS.VIEW_MEMBERSHIP,

 PERMISSIONS.CREATE_WORKOUT,
  PERMISSIONS.UPDATE_WORKOUT,
  PERMISSIONS.DELETE_WORKOUT,
  PERMISSIONS.VIEW_WORKOUT,

  PERMISSIONS.CREATE_EXERCISE,
PERMISSIONS.UPDATE_EXERCISE,
PERMISSIONS.DELETE_EXERCISE,
PERMISSIONS.VIEW_EXERCISE,
  
  ],
  

  

  [ROLES.TRAINER]: [
    PERMISSIONS.VIEW_CLIENT,

    PERMISSIONS.CREATE_WORKOUT,
    PERMISSIONS.UPDATE_WORKOUT,
    PERMISSIONS.VIEW_WORKOUT,
    PERMISSIONS.VIEW_EXERCISE,
  ],

  [ROLES.DIETITIAN]: [
    PERMISSIONS.VIEW_CLIENT,

    PERMISSIONS.CREATE_DIET_PLAN,
    PERMISSIONS.UPDATE_DIET_PLAN,
    PERMISSIONS.VIEW_DIET_PLAN,
  ],

  [ROLES.CLIENT]: [
    PERMISSIONS.VIEW_WORKOUT,
    PERMISSIONS.VIEW_DIET_PLAN,
  ],

  [ROLES.INDIVIDUAL]: [],
};