import express from "express";
import healthRoutes from "./health.routes.js";
import userRoutes from "../modules/user/user.routes.js";
import tenantRoutes from "../modules/tenant/index.js";
import dashboardRoutes from "../modules/dashboard/index.js";
import subscriptionRoutes from "../modules/subscription/index.js";
import trainerRoutes from "../modules/trainer/index.js";
import dietitianRoutes from "../modules/dietitian/index.js";
import clientRoutes from "../modules/client/index.js";
import membershipRoutes from "../modules/membership/index.js";
import workoutRoutes from "../modules/workout/index.js";
import exerciseRoutes from "../modules/exercise/index.js";
import workoutExerciseRoutes from "../modules/workoutExercise/index.js";
import attendanceRoutes from "../modules/attendance/index.js";
import progressRoutes from "../modules/progress/index.js";
import paymentRoutes from "../modules/payment/index.js";
import invoiceRoutes from "../modules/invoice/index.js";
import individualRoutes from "../modules/individual/index.js";
import expenseRoutes from "../modules/expense/index.js";
import reportRoutes from "../modules/report/index.js";
import notificationRoutes from "../modules/notification/index.js";

const router = express.Router();

router.use(healthRoutes);
router.use("/users", userRoutes);
router.use("/tenants", tenantRoutes);
router.use("/dashboards", dashboardRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/trainers", trainerRoutes);
router.use("/dietitians", dietitianRoutes);
router.use("/clients", clientRoutes);
router.use("/memberships", membershipRoutes);
router.use("/workouts", workoutRoutes);
router.use("/exercises", exerciseRoutes);
router.use("/workout-exercises",workoutExerciseRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/progress", progressRoutes);
router.use("/payments", paymentRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/individuals",individualRoutes);
router.use("/expenses",expenseRoutes);
router.use("/reports",reportRoutes);
router.use("/notifications",notificationRoutes);
export default router;